{{- with .Values.configuration.vllmToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
data:
  GENERIC_OPEN_AI_API_KEY: {{ . | b64enc }}
{{- end }}
{{- if .Values.route.oauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anythingllm.fullname" . }}-proxy-session
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
data:
  session_secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}
