{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anythingllm.serviceAccountName" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.route.oauth.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "anythingllm.fullname" . }}"}}'
    {{- end }}
automountServiceAccountToken: {{ or .Values.serviceAccount.automount .Values.route.oauth.enabled }}
{{- end }}
